import { ArrowUpRight, ArrowDown, Download, MapPin, Code2, BrainCircuit, BriefcaseBusiness } from 'lucide-react';
const linkedin = 'https://www.linkedin.com/in/arnav-hooda-87061486/';
const skills = [
  { icon: BrainCircuit, title: 'Artificial intelligence', items: ['Machine Learning', 'Deep Learning', 'Generative AI', 'LLMs & RAG', 'NLP', 'Computer Vision'] },
  { icon: Code2, title: 'Data & development', items: ['Python', 'SQL', 'React', 'Node.js', 'NumPy', 'Pandas', 'Scikit-learn', 'REST APIs'] },
  { icon: BriefcaseBusiness, title: 'Tools & foundations', items: ['Git & GitHub', 'MySQL', 'MongoDB', 'OpenCV', 'Google Colab', 'Data Structures & Algorithms'] },
];
export default function Home() {
  return (<>
    <a className="skip-link" href="#main">Skip to content</a>
    <header className="site-header wrap"><a href="#" className="wordmark" aria-label="Arnav Hooda home">arnav<span>.</span></a><nav aria-label="Main navigation"><a href="#work">Work</a><a href="#about">About</a><a href="#expertise">Expertise</a></nav><a className="header-contact" href="mailto:arnavhooda@gmail.com">Let’s talk <ArrowUpRight size={16} /></a></header>
    <main id="main">
      <section className="hero wrap" aria-labelledby="hero-title">
        <div className="hero-copy"><p className="eyebrow"><span className="status-dot" /> OPEN TO AI/ML & SOFTWARE ROLES</p><h1 id="hero-title">Curiosity.<br />Code.<br /><span>Real-world impact.</span></h1><p className="hero-intro">I’m <strong>Arnav Hooda</strong> — an AI & ML engineering student turning data and ideas into practical solutions.</p><div className="hero-actions"><a className="button primary" href="#work">Explore my work <ArrowDown size={17} /></a><a className="button text-button" href="/arnav-hooda-resume.pdf" download>Resume <Download size={17} /></a></div><div className="hero-location"><MapPin size={14} /><span>Chandigarh, India</span><span className="location-divider" /> B.E. CSE · Class of 2027</div></div>
        <div className="portrait-composition"><div className="portrait-top"><span>THE PERSON BEHIND THE CODE</span><span>01 / AH</span></div><div className="portrait-frame"><img src="/arnav-hooda.jpg" alt="Arnav Hooda wearing a navy suit" width="240" height="359" fetchPriority="high" /><div className="portrait-caption"><span>Arnav Hooda</span><span>AI / ML / SOFTWARE</span></div></div><div className="portrait-bottom"><span className="plus">+</span><span>Analytical mind.<br />Builder’s instinct.</span><a href={linkedin} target="_blank" rel="noreferrer" aria-label="Arnav Hooda on LinkedIn"><ArrowUpRight size={22} /></a></div></div>
      </section>
      <div className="focus-strip"><div className="wrap"><span>AI & MACHINE LEARNING</span><span aria-hidden="true">✳</span><span>SOFTWARE ENGINEERING</span><span aria-hidden="true">✳</span><span>ENTREPRENEURSHIP</span><span aria-hidden="true">✳</span><span>ALWAYS LEARNING</span></div></div>
      <section id="work" className="section wrap" aria-labelledby="work-title"><div className="section-heading"><div><p className="eyebrow">01 / SELECTED WORK</p><h2 id="work-title">Ideas put into practice<span>.</span></h2></div><p>From language research<br />to products built for people.</p></div>
        <article className="featured-project"><div className="research-panel"><div className="panel-top"><span>SAMSUNG R&D INSTITUTE INDIA</span><span className="small-dot" /></div><div className="research-type">Language.<br /><span>Understood.</span></div><div className="language-row" aria-hidden="true"><span>Aa</span><span>अ</span><span>語</span></div><div className="research-process"><span>DATA</span><span>→</span><span>NLP</span><span>→</span><span>IDENTIFICATION</span></div></div><div className="project-copy"><div className="project-meta"><span>RESEARCH / TEAM LEAD</span><span>2025–2026</span></div><h3>Spoken Language<br />Identification</h3><p className="project-org">Samsung PRISM Research Program</p><p>Led dataset development for a language identification system using NLP. Coordinated data collection and preprocessing to support machine learning models.</p><div className="tags"><span>NLP</span><span>Dataset development</span><span>Machine Learning</span></div><div className="project-footer"><span>April 2025 — February 2026</span><span>01</span></div></div></article>
        <div className="project-grid"><article className="project-card"><div className="project-meta"><span>WEB DEVELOPMENT</span><span>02</span></div><h3>Smart Gig</h3><p>An online marketplace connecting freelancers with businesses. Built flows for discovering projects and posting business requirements.</p><div className="tags"><span>React</span><span>Node.js</span><span>HTML</span></div><div className="project-footer"><span>June — November 2024</span><span>Freelancer marketplace</span></div></article><article className="project-card"><div className="project-meta"><span>FOUNDER / E-COMMERCE</span><span>03</span></div><h3>Elite Wristwear</h3><p>Founded and operated an online wristwear store. Managed the storefront, product listings, customer engagement, and social media marketing.</p><div className="tags"><span>Shopify</span><span>E-commerce</span><span>Business strategy</span></div><div className="project-footer"><span>August 2023 — May 2024</span><span>Independent venture</span></div></article></div>
      </section>
      <section id="about" className="about-section"><div className="wrap about-grid"><div><p className="eyebrow">02 / A LITTLE ABOUT ME</p><h2>Technical curiosity.<br /><span>Human perspective.</span></h2><p className="about-text">I’m pursuing a B.E. in Computer Science Engineering with a specialization in Artificial Intelligence & Machine Learning at Chandigarh University.</p><p className="about-text">My interests span generative AI, language models, and intelligent automation. Beyond the code, I enjoy public speaking, business strategy, fitness, and learning languages. Leading teams and building my own venture have shaped how I approach problems: with discipline, collaboration, and a willingness to learn.</p><a className="inline-link" href={linkedin} target="_blank" rel="noreferrer">Connect on LinkedIn <ArrowUpRight size={17} /></a></div><div className="milestones"><div className="milestone"><span className="milestone-label">EDUCATION</span><h3>B.E. Computer Science</h3><p>Artificial Intelligence & Machine Learning</p><div>Chandigarh University <span>2023–2027</span></div></div><div className="milestone"><span className="milestone-label">RECOGNITION</span><h3>Hack-Shastra winner</h3><p>Hackathon · 2025</p></div><div className="milestone"><span className="milestone-label">ACHIEVEMENT</span><h3>NDA-151 · AIR 621</h3><p>Cleared UPSC NDA / Service Selection Board</p></div><div className="milestone"><span className="milestone-label">LEADERSHIP</span><h3>European Union presiding officer</h3><p>IIMUN · Public speaking & diplomacy</p></div></div></div></section>
      <section id="expertise" className="section wrap" aria-labelledby="expertise-title"><div className="section-heading"><div><p className="eyebrow">03 / MY TOOLKIT</p><h2 id="expertise-title">Built on strong foundations<span>.</span></h2></div></div><div className="skills-grid">{skills.map(({icon: Icon,title,items})=><div className="skill-group" key={title}><Icon size={25} strokeWidth={1.4} /><h3>{title}</h3><div className="skill-list">{items.map(item=><span key={item}>{item}</span>)}</div></div>)}</div><div className="certifications"><p className="eyebrow">CONTINUOUS LEARNING</p><div><span>IBM Data Science Expert Certification</span><span>Samsung PRISM Research Program</span><span>Machine Learning Certification</span><span>Introduction to Programming with MATLAB</span></div></div></section>
      <section className="contact-section wrap" aria-labelledby="contact-title"><p className="eyebrow"><span className="status-dot" /> LET’S BUILD SOMETHING MEANINGFUL</p><div className="contact-row"><h2 id="contact-title">Have a challenge<br />in mind<span>?</span></h2><a className="contact-arrow" href="mailto:arnavhooda@gmail.com" aria-label="Email Arnav Hooda"><ArrowUpRight strokeWidth={1} /></a></div><div className="contact-bottom"><a className="email-link" href="mailto:arnavhooda@gmail.com">arnavhooda@gmail.com</a><p>Exploring opportunities in AI/ML,<br />data science, and software engineering.</p></div></section>
    </main>
    <footer className="wrap site-footer"><a href="#" className="wordmark">arnav<span>.</span></a><span>© 2026 Arnav Hooda</span><div><a href={linkedin} target="_blank" rel="noreferrer">LinkedIn <ArrowUpRight size={14} /></a><a href="/arnav-hooda-resume.pdf" download>Resume <Download size={14} /></a><a href="#">Back to top ↑</a></div></footer>
  </>);
}
